from typing import Literal

from fastapi import APIRouter, Body, Depends, Query
from sqlalchemy import text

from app.alerts.rules import RULES
from app.alerts.service import rules_config
from app.api.deps import parse_csv_list, require_db
from app.api.schemas import ERROR_RESPONSES, Alert, ApiResponse
from app.core.errors import NotFoundError
from app.core.events import bus
from app.core.responses import ok
from app.db.engine import connection, transaction
from app.repositories import incidents as repo

router = APIRouter(tags=["Alerts"], responses=ERROR_RESPONSES)

Severity = Literal["low", "medium", "high", "critical"]


@router.get("/alerts/rules", summary="Alert rule configuration")
def get_rules():
    """The configured alert rules and thresholds (read-only; set via environment variables)."""
    return ok(rules_config())


@router.get("/alerts", response_model=ApiResponse[list[Alert]], dependencies=[Depends(require_db)], summary="Alerts")
def get_alerts(
    status: str | None = Query(None, description="Comma-separated: open, acknowledged, resolved"),
    min_severity: Severity | None = None,
    rule: str | None = Query(None, description="Only alerts where this rule fired"),
    q: str | None = Query(None, min_length=2, max_length=100),
    hours: int | None = Query(None, ge=1, le=24 * 60, description="Last triggered within this window"),
    limit: int = Query(50, ge=1, le=500),
    offset: int = Query(0, ge=0),
    breakdown: bool = Query(False, description="Include counts by severity and by rule for these filters"),
):
    """Alerts generated by the rule engine from real incident evidence. Each alert carries its
    severity, status, location, facility, triggered rules and timestamps."""
    statuses = parse_csv_list(status, {"open", "acknowledged", "resolved"}, "status")
    if rule:
        parse_csv_list(rule, set(RULES), "rule")
    with connection() as conn:
        rows, total = repo.list_alerts(
            conn, statuses=statuses, min_severity=min_severity, limit=limit, offset=offset, rule=rule, q=q, hours=hours
        )
        counts = {
            r[0]: r[1]
            for r in conn.execute(
                text("SELECT status, count(*) FROM alerts GROUP BY status")
            )
        }
        extra = (
            {"breakdown": repo.alert_breakdown(conn, statuses=statuses, min_severity=min_severity, rule=rule, q=q, hours=hours)}
            if breakdown
            else {}
        )
    return ok(rows, {"total": total, "count": len(rows), "limit": limit, "offset": offset, "by_status": counts, **extra})


@router.get("/alerts/{alert_id}", dependencies=[Depends(require_db)], summary="Alert detail with evidence")
def get_alert(alert_id: int):
    with connection() as conn:
        alert = repo.get_alert(conn, alert_id)
    if not alert:
        raise NotFoundError(f"Alert {alert_id} not found")
    return ok(alert)


@router.post("/alerts/{alert_id}/acknowledge", dependencies=[Depends(require_db)], summary="Acknowledge an alert")
def acknowledge_alert(alert_id: int):
    with transaction() as conn:
        row = repo.acknowledge_alert(conn, alert_id)
    if not row:
        raise NotFoundError(f"Alert {alert_id} not found")
    bus.publish("alert.acknowledged", {"alert_id": alert_id})
    return ok(row)


@router.post("/alerts/{alert_id}/resolve", dependencies=[Depends(require_db)], summary="Resolve an alert")
def resolve_alert(alert_id: int, note: str | None = Body(None, embed=True, max_length=500)):
    with transaction() as conn:
        row = repo.resolve_alert(conn, alert_id, note)
    if not row:
        raise NotFoundError(f"Alert {alert_id} not found")
    bus.publish("alert.resolved", {"alert_id": alert_id})
    return ok(row)
