import { useState } from 'react';
import { Database, ExternalLink, FlaskConical, Play } from 'lucide-react';
import { api } from '../api/client.js';
import { useApi } from '../hooks/useApi.js';
import { useApp } from '../state/AppContext.jsx';
import { fmtInt, fmtRelative, fmtUtc, titleCase } from '../utils/format.js';
import { StatusBadge } from '../components/common/Badges.jsx';
import { Badge, Button, EmptyState, ErrorState, SkeletonRows } from '../components/common/ui.jsx';
import s from './page.module.css';
import d from './DataSourcesView.module.css';

const CATEGORY = {
  thermal: 'Thermal detections',
  infrastructure: 'Industrial infrastructure',
  land_cover: 'Land cover',
  boundary: 'Monitoring boundary',
  imagery: 'Satellite imagery',
  database: 'Database',
};

const RUN_TONE = { success: 'ok', partial: 'warn', failed: 'err', running: 'accent' };
const EVENT_TONE = { error: 'err', warning: 'warn', info: 'idle', debug: 'idle' };

function SourceCard({ src }) {
  const run = src.latest_run;
  return (
    <article className={d.source}>
      <header className={d.sourceHead}>
        <div>
          <div className={d.category}>{CATEGORY[src.category] || titleCase(src.category)}</div>
          <h2 className={d.sourceName}>{src.name}</h2>
        </div>
        <StatusBadge status={src.status} />
      </header>
      <p className={d.desc}>{src.description}</p>
      {src.status_message && <p className={d.message}>{src.status_message}</p>}
      <dl className={d.facts}>
        <dt>Provider</dt>
        <dd>{src.provider}</dd>
        {src.mode && (
          <>
            <dt>Access mode</dt>
            <dd>{src.mode === 'api' ? 'FIRMS Area API (MAP_KEY configured)' : 'FIRMS public NRT feed (no MAP_KEY)'}</dd>
          </>
        )}
        <dt>Last success</dt>
        <dd title={fmtUtc(src.last_success_at)}>{src.last_success_at ? `${fmtRelative(src.last_success_at)} · ${fmtUtc(src.last_success_at)}` : '—'}</dd>
        {src.last_record_count != null && (
          <>
            <dt>Records</dt>
            <dd className="mono">{fmtInt(src.last_record_count)}</dd>
          </>
        )}
        {src.latency_ms != null && (
          <>
            <dt>Latency</dt>
            <dd className="mono">{src.latency_ms} ms</dd>
          </>
        )}
        {run && (
          <>
            <dt>Latest run</dt>
            <dd>
              <Badge tone={RUN_TONE[run.status] || 'idle'}>{titleCase(run.status)}</Badge>{' '}
              <span className={s.muted}>
                #{run.id} · {fmtRelative(run.started_at)} · {fmtInt(run.records_inserted)} new
              </span>
            </dd>
          </>
        )}
        {src.last_error && (
          <>
            <dt>Last error</dt>
            <dd className={d.error}>{src.last_error}</dd>
          </>
        )}
        {src.license && (
          <>
            <dt>Licence</dt>
            <dd>{src.license}</dd>
          </>
        )}
      </dl>
      {src.url && (
        <a className={d.link} href={src.url} target="_blank" rel="noreferrer">
          {new URL(src.url).host} <ExternalLink size={11} />
        </a>
      )}
    </article>
  );
}

export default function DataSourcesView({ embedded = false }) {
  const { pipeline, setPipeline, pushToast } = useApp();
  const sources = useApi('/api/data-sources', null, { interval: 30000 });
  const runs = useApi('/api/ingestion-runs', { limit: 15 }, { interval: pipeline.running ? 5000 : 0 });
  const events = useApi('/api/system-events', { limit: 40 });
  const status = useApi('/api/pipeline/status', null, { interval: 5000 });
  const health = useApi('/api/health', null, { live: false });
  const [starting, setStarting] = useState(false);
  const running = pipeline.running || status.data?.running;
  const testMode = health.data?.data_mode === 'test-fixture';
  const triggerOpen = health.data?.pipeline_trigger === 'open';
  const pollMinutes = health.data?.scheduler?.jobs?.find?.((j) => j.id === 'pipeline_cycle')?.interval_minutes;

  async function replayFixture() {
    setStarting(true);
    try {
      const { data } = await api.post('/api/demo/replay');
      pushToast({
        tone: 'info',
        title: 'Test fixture replayed',
        body: `${data.detections_inserted} labelled detections, ${data.alerts_created} alert(s) generated by the alert engine.`,
      });
      status.reload();
      runs.reload();
    } catch (e) {
      pushToast({ tone: 'error', title: 'Replay failed', body: e.message });
    } finally {
      setStarting(false);
    }
  }

  async function runPipeline() {
    setStarting(true);
    try {
      await api.post('/api/pipeline/run');
      setPipeline({ running: true, job: 'pipeline' });
      pushToast({ tone: 'info', title: 'Pipeline started', body: 'Ingestion and analysis are running. Progress streams live.' });
      status.reload();
    } catch (e) {
      pushToast({ tone: 'error', title: 'Could not start pipeline', body: e.message });
    } finally {
      setStarting(false);
    }
  }

  const Title = embedded ? 'h2' : 'h1';
  return (
    <div className={embedded ? undefined : s.page}>
      <div className={s.header}>
        <div>
          <Title className={s.title}>Data sources & pipeline</Title>
          <p className={s.subtitle}>
            Every map layer and metric is derived from these sources. Coverage is limited to India's official boundary and its
            Exclusive Economic Zone; anything outside is discarded at ingestion.
          </p>
        </div>
        <div className={s.controls}>
          {status.data?.job && <span className={s.muted}>Running: {titleCase(status.data.job)}</span>}
          {status.data?.last_finished_at && !running && (
            <span className={s.muted}>
              Last run {fmtRelative(status.data.last_finished_at)} ({status.data.last_status || '—'})
            </span>
          )}
          {testMode && (
            <Button icon={FlaskConical} onClick={replayFixture} disabled={starting || running}>
              Replay test fixture
            </Button>
          )}
          {!testMode && triggerOpen && (
            <Button variant="primary" icon={Play} onClick={runPipeline} disabled={starting || running}>
              {running ? 'Pipeline running…' : 'Run pipeline now'}
            </Button>
          )}
          {!testMode && health.data && !triggerOpen && (
            <span className={s.muted}>Runs automatically{pollMinutes ? ` every ${pollMinutes} min` : ' on schedule'} (operator trigger requires the admin token)</span>
          )}
        </div>
      </div>

      {sources.loading && <SkeletonRows rows={3} height={160} gap={12} />}
      {sources.error && <ErrorState error={sources.error} onRetry={sources.reload} />}
      {sources.data && (
        <div className={d.grid}>
          {sources.data.map((src) => (
            <SourceCard key={src.id} src={src} />
          ))}
        </div>
      )}

      <div className={d.lower}>
        <section className={`${s.card} ${s.tableCard}`}>
          <h2 className={d.blockTitle}>Recent runs</h2>
          {runs.error && <ErrorState error={runs.error} onRetry={runs.reload} compact />}
          {runs.data?.length === 0 && (
            <EmptyState icon={Database} title="No runs yet">
              Start the pipeline to ingest FIRMS detections and OpenStreetMap facilities.
            </EmptyState>
          )}
          {runs.data?.length > 0 && (
            <table className={s.table}>
              <thead>
                <tr>
                  <th>Run</th>
                  <th>Job</th>
                  <th>Status</th>
                  <th className={s.num}>Fetched</th>
                  <th className={s.num}>Valid</th>
                  <th className={s.num}>New</th>
                  <th>Started</th>
                  <th>Duration</th>
                </tr>
              </thead>
              <tbody>
                {runs.data.map((r) => (
                  <tr key={r.id} title={r.error || ''}>
                    <td className="mono">#{r.id}</td>
                    <td>{titleCase(r.job)}</td>
                    <td>
                      <Badge tone={RUN_TONE[r.status] || 'idle'}>{titleCase(r.status)}</Badge>
                    </td>
                    <td className={`${s.num} mono`}>{fmtInt(r.records_fetched)}</td>
                    <td className={`${s.num} mono`}>{fmtInt(r.records_valid)}</td>
                    <td className={`${s.num} mono`}>{fmtInt(r.records_inserted)}</td>
                    <td className={s.nowrap} title={fmtUtc(r.started_at)}>
                      {fmtRelative(r.started_at)}
                    </td>
                    <td className="mono">
                      {r.finished_at ? `${Math.max(1, Math.round((new Date(r.finished_at) - new Date(r.started_at)) / 1000))} s` : '…'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </section>

        <section className={s.card}>
          <h2 className={d.blockTitle}>System events</h2>
          {events.error && <ErrorState error={events.error} onRetry={events.reload} compact />}
          {events.data?.length === 0 && <EmptyState title="No events yet" />}
          <ul className={d.events}>
            {events.data?.map((e) => (
              <li key={e.id} className={d.event}>
                <Badge tone={EVENT_TONE[e.severity] || 'idle'}>{e.severity}</Badge>
                <div className={d.eventBody}>
                  <div className={d.eventMsg}>{e.message}</div>
                  <div className={s.muted}>
                    <span className="mono">{e.event_type}</span> · {fmtRelative(e.created_at)}
                  </div>
                </div>
              </li>
            ))}
          </ul>
        </section>
      </div>
    </div>
  );
}
